spring:
  jpa:
    show-sql: true
  # 数据库配置
  datasource:
    url: jdbc:mysql://47.94.167.203/whellsurf?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 19980715
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  resources:
     static-locations: classpath:/static, classpath:/static/page
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
wx:
  mp:
    configs:
      - appId:  wx55cd46481d4e28d6
        secret: 77fc6fc8fd2fb85d8c4f7c5b5dba5fd4
        token: 123456
        aesKey: yzJVNFDeIUyYMAWt8dBoFaWtSyAhdlfhWUSfSwi0ktD